//
// Created by mk on 27.03.2017.
//

#ifndef JIMP_EXERCISES_MULTIPLICATIONTABLE_H
#define JIMP_EXERCISES_MULTIPLICATIONTABLE_H


void MultiplicationTable(int tab[][10]);

#endif //JIMP_EXERCISES_MULTIPLICATIONTABLE_H
